CREATE SCHEMA PB

CREATE TABLE PB.Logs 
(
	Id INT IDENTITY,
	LogLevel NVARCHAR(100),
	TimeLogged DATETIME2,
	LogMessage NVARCHAR(MAX),
	PRIMARY KEY (ID)
)

CREATE TABLE PB.Invoice
(
	Id INT IDENTITY NOT NULL,
	OrderHeaderId INT NULL,
	OrderPlaced BIT NOT NULL,
	TimePlaced DATETIME2 NOT NULL,
	PRIMARY KEY (Id)
)

CREATE TABLE PB.People
(
	Id INT IDENTITY NOT NULL,
	FirstName NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	StreetAddress NVARCHAR(200) NOT NULL,
	ZIPCode NVARCHAR(10) NOT NULL,
	CompanyNameId INT NULL,
	PRIMARY KEY (Id)
)

CREATE TABLE PB.Company
(
	Id INT IDENTITY NOT NULL,
	CompanyName NVARCHAR(100) NOT NULL,
	PRIMARY KEY (Id)
)

CREATE TABLE PB.OrderHeaders
(
	Id INT IDENTITY NOT NULL,
	BillingPersonId INT NOT NULL,
	ShippingPersonId INT NOT NULL,
	PhoneNumber NVARCHAR(13) NOT NULL,
	EmailAddress NVARCHAR(100) NULL,
	PRIMARY KEY (Id)
)

CREATE TABLE PB.OrderDetail
(
	Id INT IDENTITY NOT NULL,
	OrderHeaderId INT NOT NULL,
	ProductId INT NOT NULL,
	Quantity INT NOT NULL,
	Notes NVARCHAR(MAX) NULL,
	Status NVARCHAR(MAX) NULL,
	PRIMARY KEY (Id)
)

CREATE TABLE PB.Products
(
	Id INT IDENTITY NOT NULL,
	ProductName NVARCHAR(100) NOT NULL,
	ProductTypeId INT NULL,
	PRIMARY KEY (Id)
)

CREATE TABLE PB.ProductType
(
	Id INT IDENTITY NOT NULL,
	TypeName NVARCHAR(100) NOT NULL,
	PRIMARY KEY (Id)
)

ALTER TABLE PB.OrderHeaders
	ADD CONSTRAINT FK_OrderHeaders_People FOREIGN KEY (BillingPersonId) REFERENCES PB.People(Id);
ALTER TABLE PB.OrderHeaders
	ADD CONSTRAINT FK_OrderHeaders_People_ShippingPersonId FOREIGN KEY (ShippingPersonId) REFERENCES PB.People(Id);

ALTER TABLE PB.OrderDetail
	ADD CONSTRAINT FK_OrderDetail_OrderHeaders_OrderHeaderId FOREIGN KEY (OrderHeaderId) REFERENCES PB.OrderHeaders(Id);
ALTER TABLE PB.OrderDetail
	ADD CONSTRAINT FK_OrderDetail_Products_ProductId FOREIGN KEY (ProductId) REFERENCES PB.Products(Id);

ALTER TABLE PB.Products
	ADD CONSTRAINT FK_Products_ProductType_ProductTypeId FOREIGN KEY (ProductTypeId) REFERENCES PB.ProductType(Id);

ALTER TABLE PB.People
	ADD CONSTRAINT FK_People_Company_CompanyId FOREIGN KEY (CompanyNameId) REFERENCES PB.Company(Id);

ALTER TABLE PB.Invoice
	ADD CONSTRAINT FK_Invoice_OrderHeaders_OrderHeaderId FOREIGN KEY (OrderHeaderId) REFERENCES PB.OrderHeaders(Id);
