CREATE SCHEMA PB

CREATE TABLE PB.Logs 
(
	Id INT IDENTITY,
	LogLevel NVARCHAR(100),
	TimeLogged DATETIME2,
	LogMessage NVARCHAR(MAX),
	PRIMARY KEY (ID)
)

CREATE TABLE PB.Invoice
(
	Id INT IDENTITY NOT NULL,
	OrderHeaderId INT NULL,
	OrderPlaced BIT NOT NULL,
	TimePlaced DATETIME2 NOT NULL,
	PRIMARY KEY (Id)
)

CREATE TABLE PB.People
(
	Id INT IDENTITY NOT NULL,
	FirstName NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	StreetAddress NVARCHAR(200) NOT NULL,
	ZIPCode NVARCHAR(10) NOT NULL,
	CompanyNameId INT NULL,
	PRIMARY KEY (Id)
)

CREATE TABLE PB.Company
(
	Id INT IDENTITY NOT NULL,
	CompanyName NVARCHAR(100) NOT NULL,
	PRIMARY KEY (Id)
)

CREATE TABLE PB.OrderHeaders
(
	Id INT IDENTITY NOT NULL,
	BillingPersonId INT NOT NULL,
	ShippingPersonId INT NOT NULL,
	PhoneNumber NVARCHAR(13) NOT NULL,
	EmailAddress NVARCHAR(100) NULL,
	PRIMARY KEY (Id)
)

CREATE TABLE PB.OrderDetail
(
	Id INT IDENTITY NOT NULL,
	OrderHeaderId INT NOT NULL,
	ProductId INT NOT NULL,
	Quantity INT NOT NULL,
	Notes NVARCHAR(MAX) NULL,
	Status NVARCHAR(MAX) NULL,
	PRIMARY KEY (Id)
)

CREATE TABLE PB.Products
(
	Id INT IDENTITY NOT NULL,
	ProductName NVARCHAR(100) NOT NULL,
	ProductTypeId INT NULL,
	PRIMARY KEY (Id)
)

CREATE TABLE PB.ProductType
(
	Id INT IDENTITY NOT NULL,
	TypeName NVARCHAR(100) NOT NULL,
	PRIMARY KEY (Id)
)